<a href="https://colab.research.google.com/github/iSanaAfzal/syntecxhub-DataScience-Analysis/blob/main/Numpy_Data_Explorer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

print("NumPy Version:", np.__version__)

NumPy Version: 2.0.2


In [ ]:
arr1 = np.array([10, 20, 30, 40, 50])
print(arr1)

[10 20 30 40 50]


In [ ]:
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr2)

[[1 2 3]
 [4 5 6]]


In [ ]:
zeros = np.zeros((3,3))
ones = np.ones((2,2))
identity = np.eye(4)

print("Zeros Array:\n", zeros)
print("\nOnes Array:\n", ones)
print("\nIdentity Matrix:\n", identity)

Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Ones Array:
 [[1. 1.]
 [1. 1.]]

Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
data = np.array([[1,2,3],[4,5,6]])

print("Shape:", data.shape)
print("Dimensions:", data.ndim)
print("Size:", data.size)
print("Data Type:", data.dtype)

Shape: (2, 3)
Dimensions: 2
Size: 6
Data Type: int64


In [ ]:
arr = np.array([10,20,30,40,50])

print("First Element:", arr[0])
print("Third Element:", arr[2])
print("Last Element:", arr[-1])

First Element: 10
Third Element: 30
Last Element: 50


In [ ]:
arr = np.array([10,20,30,40,50,60])

print(arr[1:4])
print(arr[:3])
print(arr[3:])
print(arr[::-1])

[20 30 40]
[10 20 30]
[40 50 60]
[60 50 40 30 20 10]


In [ ]:
matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print("Element:", matrix[1,2])
print("Row:", matrix[1])
print("Column:", matrix[:,1])

Element: 6
Row: [4 5 6]
Column: [2 5 8]


In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


In [ ]:
data = np.array([10,20,30,40,50])

print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Max:", np.max(data))
print("Min:", np.min(data))
print("Standard Deviation:", np.std(data))

Mean: 30.0
Median: 30.0
Max: 50
Min: 10
Standard Deviation: 14.142135623730951


In [ ]:
matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print("Column Sum:", np.sum(matrix, axis=0))
print("Row Sum:", np.sum(matrix, axis=1))

print("Column Mean:", np.mean(matrix, axis=0))
print("Row Mean:", np.mean(matrix, axis=1))

Column Sum: [12 15 18]
Row Sum: [ 6 15 24]
Column Mean: [4. 5. 6.]
Row Mean: [2. 5. 8.]


In [ ]:
arr = np.arange(12)

print("Original:")
print(arr)

reshaped = arr.reshape(3,4)

print("\nReshaped:")
print(reshaped)

Original:
[ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
matrix = np.array([
    [1,2,3],
    [4,5,6]
])

flat = matrix.flatten()

print(flat)

[1 2 3 4 5 6]


In [ ]:
matrix = np.array([
    [1,2,3],
    [4,5,6]
])

result = matrix + 10

print(result)

[[11 12 13]
 [14 15 16]]


In [ ]:
matrix = np.array([
    [1,2,3],
    [4,5,6]
])

vector = np.array([10,20,30])

result = matrix + vector

print(result)

[[11 22 33]
 [14 25 36]]


In [ ]:
dataset = np.random.randint(1, 100, size=(5,4))

print(dataset)

[[37 27 70  7]
 [52 94 74 34]
 [59 24 69 42]
 [42 36 98 83]
 [77 28 93 37]]


In [ ]:
dataset = np.random.randint(1,100,size=(5,4))

print("Dataset:\n")
print(dataset)

print("\nMean:", np.mean(dataset))
print("Max:", np.max(dataset))
print("Min:", np.min(dataset))

print("\nColumn Means:")
print(np.mean(dataset, axis=0))

print("\nRow Means:")
print(np.mean(dataset, axis=1))

Dataset:

[[13 47 54 62]
 [ 9  6 54 41]
 [90 59 19 63]
 [56  6 66 37]
 [55 33 15 11]]

Mean: 39.8
Max: 90
Min: 6

Column Means:
[44.6 30.2 41.6 42.8]

Row Means:
[44.   27.5  57.75 41.25 28.5 ]


In [ ]:
dataset = np.random.randint(1,100,size=(5,4))

np.save("dataset.npy", dataset)

print("File Saved Successfully")

File Saved Successfully


In [ ]:
loaded_data = np.load("dataset.npy")

print(loaded_data)

[[19 51 20 56]
 [57 48 98 65]
 [36 57 95 31]
 [39 58 81 84]
 [93 17 30 11]]


In [ ]:
import time

size = 1000000

# Python List
list1 = list(range(size))
list2 = list(range(size))

start = time.time()
result = [x+y for x,y in zip(list1,list2)]
end = time.time()

print("Python List Time:", end-start)

Python List Time: 0.07072639465332031


In [ ]:
import time

arr1 = np.arange(1000000)
arr2 = np.arange(1000000)

start = time.time()
result = arr1 + arr2
end = time.time()

print("NumPy Time:", end-start)

NumPy Time: 0.02164745330810547


In [ ]:
import numpy as np
import time

# Large arrays create karo
arr1 = np.arange(1000000)
arr2 = np.arange(1000000)

# NumPy performance test
start = time.time()
result = arr1 + arr2
end = time.time()

print("NumPy Time:", end - start)

NumPy Time: 0.0019443035125732422


In [ ]:
import numpy as np

data = np.random.randint(1,100,size=(5,5))

print("DATASET")
print(data)

print("\nShape:", data.shape)
print("Dimensions:", data.ndim)

print("\nMean:", np.mean(data))
print("Median:", np.median(data))
print("Maximum:", np.max(data))
print("Minimum:", np.min(data))

print("\nColumn Sum:")
print(np.sum(data, axis=0))

print("\nRow Sum:")
print(np.sum(data, axis=1))

reshaped = data.reshape(1,25)

print("\nReshaped Data:")
print(reshaped)

np.save("final_dataset.npy", data)

loaded = np.load("final_dataset.npy")

print("\nLoaded Dataset:")
print(loaded)

DATASET
[[67 11 22 47 13]
 [25 51 34 62 83]
 [72 18 20 28 13]
 [16 40 76 48 42]
 [59 31 25 17 21]]

Shape: (5, 5)
Dimensions: 2

Mean: 37.64
Median: 31.0
Maximum: 83
Minimum: 11

Column Sum:
[239 151 177 202 172]

Row Sum:
[160 255 151 222 153]

Reshaped Data:
[[67 11 22 47 13 25 51 34 62 83 72 18 20 28 13 16 40 76 48 42 59 31 25 17
  21]]

Loaded Dataset:
[[67 11 22 47 13]
 [25 51 34 62 83]
 [72 18 20 28 13]
 [16 40 76 48 42]
 [59 31 25 17 21]]


In [ ]:
%cd /content/syntecxhub-DataScience-Analysis

/content/syntecxhub-DataScience-Analysis


In [ ]:
!rm -rf syntecxhub-DataScience-Analysis
!git clone https://github.com/iSanaAfzal/syntecxhub-DataScience-Analysis.git

Cloning into 'syntecxhub-DataScience-Analysis'...
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 5 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (5/5), done.


In [ ]:
%cd /content/syntecxhub-DataScience-Analysis

/content/syntecxhub-DataScience-Analysis


In [ ]:
%cd /content/syntecxhub-DataScience-Analysis

/content/syntecxhub-DataScience-Analysis


In [ ]:
!pwd

/content/syntecxhub-DataScience-Analysis


In [ ]:
!ls

syntecxhub-DataScience-Analysis


In [ ]:
!find /content -name "*.ipynb"

In [ ]:
!find /content -name "*.ipynb"

In [ ]:
!git rm --cached syntecxhub-DataScience-Analysis

rm 'syntecxhub-DataScience-Analysis'


In [ ]:
%cd /content
!rm -rf syntecxhub-DataScience-Analysis

/content


In [ ]:
!git clone https://github.com/iSanaAfzal/syntecxhub-DataScience-Analysis.git
%cd syntecxhub-DataScience-Analysis

Cloning into 'syntecxhub-DataScience-Analysis'...
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (3/3), done.
Receiving objects: 100% (5/5), done.
remote: Total 5 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
/content/syntecxhub-DataScience-Analysis


In [ ]:
!find /content -name "*.ipynb"

In [ ]:
!cp "/content/Numpy Data_Explorer.ipynb" .
!git add .
!git commit -m "Add notebook"
!git push origin main

cp: cannot stat '/content/Numpy Data_Explorer.ipynb': No such file or directory
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
fatal: could not read Username for 'https://github.com': No such device or address
